sudo: required
services:
  - docker

language: go

go:
  - 1.5.1

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - make pull-images
  # uncomment to build fresh images
  # - make images
  # - make push-images
  - make deps
  - make

deploy:
  provider: s3
  access_key_id: AKIAIAXUU3N2C6EHT5GQ
  secret_access_key:
    secure: VG6DjUxIf4A1Im2XEXNpzDYxCtQxFCdWs7loKmrXl3r6W/EGiBV0CaZ8f2qqh6sV/jRYegc3J8Qq0R6T4aVDoGznArxmLYOXa1stTuO5l5K0y79CYCypkv7XlYi0cUG9iHmTRi8X+Im4P1FZl8n8q1s8YhHguLIRvhvCGjHGYm/OqdM6RVAEMwjDNTT2SdAaILnmJWdjz6TVjHU9dwuses+0gQww2kYSyWm6c86TiDjwTLcLJWhh2QJXbUcaNeu646Y/imcjdQ0UZuxmz63cO7cdeOs2jejwuFGq0ABfZPtUF7Rm1k9e/HxCzGc5m5XYutnHm8+1gh8UMBojNR/kQkPcO8YpERIGy85ndEnmWxSKXWLF6aH23EtWVDGQrWue92eXrCwkrHqNrJFoB87f7xL/sSgf/u08nC6DCZhQE22RJrKaw9cw9lUqg6ExtVmAM5TKrt1KuVD2ehI+3Ml8GN6HCIZxSmLfze6nuYwaXTKC4gCYL+QQYhbPOvpyMH6Mumh4m7Z2EwXW/LGje/dMWYO/YFQ+TjUYnfElAMvAgKmMzmUP2aZcKHR6o1urftW16iYys8GRpbr3lG+Gnvzpl8qMA8Px8c8xXPgoRxJJzRnITBIJndx2LknpNN8VD4nbGPqXFirFG1kwVd87osa0Ogg2kxlwkxJqXyuZWjgIuGA=
  bucket: beats-nightlies
  local-dir: build/upload
  acl: public_read
  on:
    repo: elastic/beats-packer
    branch: master

notifications:
  hipchat:
    rooms:
      secure: IwewLTgVj64YtDcEGaBAdSXOxKB8YSiFXuPYFQV7pBAQoGwpTlVR8MDOdTPb52mbnFyMhcxTp9fKPbUIpZJoQFMspmqjCmT3CWXAOHDpNRGdsV7/e2WuCzwB0CVFPBf7HcfKAQwWyw70hAegWztZDA/sFb3UhIk/igR9X43GpYikUkQcydN9zjXOYXi5wa+1n1EP6teIk7pBOlN1nN3B2cSY7lfgekpWYEnwObcLs3JLNOK3jnI1lgprr4lwJuainDAytKs8AqURFkCxl1cMGbLn/ul4LsHdrl4j5vsOcwLeKez6vc/6CyDfBs+AeHK47ILpiXmeAuOYsBBAlFaYgp+pHLaN2Kz7HNBxkwbN+LhmygrNeSVJLipxmwsPMt7yWZOQGUb00+Kfks1Zh4CbTZk3cFIk2zZIwYaSPD2lBsuVrHBbfCNc9dcbzA9/bLaaWBpX2uNVhTNCVuCVA19gBJkTZpEbNhdnZp5Xi8+Oi1V8t5qxK14r96qbNVySnROiEijw2TkgmdVh+NKEYgtK6NIDmZYq7BgLClz7bLIfzv9jSByKe05lG8mW34fPbHhbnhMiyBat0Nv8xHXTWAtN2IS7xhzAP3R7/frA5K5b0FEPZUNkxdgA1IVqC23gJTk/gRNKgN8GdlxnCSAnidVMD6laMFRG4GkOFDO9OLWpvZ4=
